### ISSUE TITLE
Device token should persist

### ISSUE THREAD

**Issue by jordanstreiff** [coalest/remarkable_ruby#1]
Currently every time you create a client we are creating a new reMarkable app to get the device token. Instead, we want to save the device token locally in a file. If the file exists, then we use that token instead of creating a new app.

**Comment by coalest** [comment]
In keeping with the format from other rM API tools I've seen, the tokens are loaded/saved in a config file named ".rmapi" in the user's home directory. 

The `Dir::home` method was used to get the home folder of the user. It should work in Mac, Windows, and Linux, although so far I've only tested it in Linux ofc.

https://github.com/coalest/remarkable-ruby/commit/4e7a93a324ea3a3495385c5e3e1af7e74b18247d
